### ISSUE TITLE
better pg-promise usage

### ISSUE THREAD

**Issue by vitaly-t** [Swaven/node-db-connector#1]
Since the purpose of this is only to test the connection, a better way with pg-promise would be...

use `db.connect({direct: true})` to connect and then `obj.done()` to disconnect. This will bypass the creation of the connection pool internally, which you don't even need for this module ;)

And as a result, you will not need to call `pgp.end()` at all.

**Comment by antoinegoutagny** [comment]
Although this module only tests the connection, the exposed db object is used by dependants to perform actual queries. So we need to use the connection pool.

**Comment by vitaly-t** [comment]
Ok, if you plan to execute queries then you do need to use the pool, I didn't spot that part.
