### ISSUE TITLE
Need help in establishing DBConnection

### ISSUE THREAD

**Issue by bandarudivya** [Swaven/node-db-connector#3]
Hi ,
Thanks for the node-db-connector ,it really helped me I'm trying to establish two database connections (postgresql and mongodb).I followed the instructions given in the module and tried to print the db object,the console shows promise object for mongoose connection.But for postgresql connection it is showing as Pending.
Please check the below link
https://user-images.githubusercontent.com/26456636/27913228-104202a6-627d-11e7-82d4-723358b92419.png
 I'm a beginner so correct me if im wrong.

**Comment by antoinegoutagny** [comment]
Hi,

Can you share the code where you use the package? That would help finding the cause.

**Comment by bandarudivya** [comment]
Thank you so much for your reply.Here is my code,
`const pgp = require('pg-promise')();  
 var db = require('node-db-connector');

        configs = [{
			  name: ['Employees'],
			connectionString: 'postgresql://admin:password@localhost:5432/Employees'

			},{
          name: ['sample'],
			connectionString :'mongodb://localhost:27017/sample',
			mongoose: true
        }]
    db.init(configs, {mongoose
	});
var app = express();
console.log(pgp);`

**Comment by antoinegoutagny** [comment]
Ok, I see the problem. The `init` method is asynchronous and returns a promise. Here's what you should do:

```javascript

const mongoose = require('mongoose'),
      express = require('express'),
      db = require('node-db-connector');

var configs = [{
    name: 'Employees',
    connectionString: 'postgresql://admin:password@localhost:5432/Employees'
},{
    name: 'sample',
    connectionString :'mongodb://localhost:27017/sample',
    mongoose: true
}]

db.init(configs, {mongoose: mongoose})
.then(() => {
    // now you are connected to all databases
    var app = express();
    console.log(db.Employees)
})
.catch(err => {
    console.error(err)
})
```

A few things to note:
- you don't need to require `pgpromise`, it's embedded by `node-db-connector`;
- the mongoose object must be passed as the `mongoose` property in the options;
- `name` property can be a string if there is only one db to connect to for a single connection string.

If you are not familiar with promises, I suggest you [read about them](https://www.sitepoint.com/overview-javascript-promises/). It's a very simple way to make asynchronous code easy to write and understand.

**Comment by bandarudivya** [comment]
The above shared information was useful. Thankyou so much for the help.
